name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main  # Change to your branch name if it's not 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
